version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
    container_name: spring-backend

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: angular-frontend
