spring:
  application:
    name: izertis-tech-test-elliot

movies:
  provider: omdb
  tmdb:
    base-url: https://api.themoviedb.org/3
    api-key: ${TMDB_API_KEY}
  omdb:
    base-url: https://www.omdbapi.com/
    api-key: ${OMDB_API_KEY}
