spring:
  application:
    name: izertis-tech-test-elliot
  webflux:
    problemdetails:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

jwt:
  secret: ${JWT_AUTH_SECRET}
  expiration: 60m

movies:
  provider: omdb
  tmdb:
    base-url: https://api.themoviedb.org/3
    api-key: ${TMDB_API_KEY}
  omdb:
    base-url: https://www.omdbapi.com/
    api-key: ${OMDB_API_KEY}
